/**
 * Express Type Extensions
 *
 * Extends Express.Request interface to include custom properties
 * added by middleware and used throughout the application.
 *
 * This file uses TypeScript's "declaration merging" to augment
 * the Express namespace with additional properties.
 *
 * @see https://www.typescriptlang.org/docs/handbook/declaration-merging.html
 */

declare namespace Express {
  /**
   * Extended Request interface with custom properties
   */
  export interface Request {
    /**
     * Correlation ID for request tracking
     *
     * Added by: CorrelationIdMiddleware
     * Used by: Guards, Interceptors, Filters, Controllers
     *
     * Format: req-{timestamp}-{random}
     * Example: req-ljh9k3d-8x7v2w9pq
     *
     * Source:
     * - Extracted from incoming headers (distributed tracing)
     * - Generated by middleware if not provided (standalone operation)
     *
     * @see CorrelationIdMiddleware
     */
    correlationId?: string;
  }
}
